title               : Ashutosh Raina's Blog
description         : Hacker is a theme for GitHub Pages.
show_downloads      : false
google_analytics    :
theme               : jekyll-theme-hacker
locale              : "en-US"
